### Get all hostels
GET http://localhost:4004/hostels
Accept: application/json

###

### Create a new hostel
POST http://localhost:4004/hostels
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "Zakir C",
  "hasAC": true,
  "numberOfRooms": 700,
  "isBoysHostel": true,
  "chargesPerSemester": 70000
}

###

### Update an existing hostel
PUT http://localhost:4004/hostels/db4954b0-8337-4b60-a10e-32786d437ce3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "NC2",
  "hasAC": false,
  "numberOfRooms": 120,
  "numberOfSeatsPerRoom": 3,
  "isBoysHostel": false,
  "chargesPerSemester": 5000
}

###
GET http://localhost:4004/hostels/db4954b0-8337-4b60-a10e-32786d437ce3/is-boys
Accept: application/json
Authorization: Bearer {{token}}
### Delete a hostel
DELETE http://localhost:4004/hostels/6d77df19-9a89-4776-bfa1-661500d2081b
Accept: application/json

