### Get all hostels
GET http://localhost:4001/hostels
Accept: application/json

###

### Create a new hostel
POST http://localhost:4001/hostels
Content-Type: application/json
Accept: application/json

{
  "name": "Zakir A",
  "hasAC": true,
  "numberOfRooms": 100,
  "numberOfSeatsPerRoom": 2,
  "isBoysHostel": true,
  "chargesPerSemester": 5000
}

###

### Update an existing hostel
PUT http://localhost:4001/hostels/28b1e2ed-e61a-4af8-8a80-36d0fc433ee2
Content-Type: application/json
Accept: application/json

{
  "name": "Zakir A - Updated",
  "hasAC": false,
  "numberOfRooms": 120,
  "numberOfSeatsPerRoom": 3,
  "isBoysHostel": false,
  "chargesPerSemester": 5000
}

###

### Delete a hostel
DELETE http://localhost:4001/hostels/{{hostelId}}
Accept: application/json
