### Approve a request
PATCH http://localhost:4003/requests/6903c9c8869a9f85b57394ac/status?status=APPROVED&reviewedBy=warden2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
