### Approve a request
PATCH http://localhost:4003/requests/690593da03835fc6c7bc027d/status?status=APPROVED&reviewedBy=warden2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
